"""
Gemma AI Security Advisor Connector
====================================
Queries the local Ollama instance on port 11434 to generate high-impact,
personalized security advisories for employees who receive phishing emails.
"""

import logging
import requests
import json
from typing import List, Dict, Any

logger = logging.getLogger(__name__)

OLLAMA_URL = "http://localhost:11434"

def get_installed_gemma_model() -> str:
    """
    Queries Ollama to find installed models.
    Prioritizes models containing 'gemma' in the name.
    """
    try:
        resp = requests.get(f"{OLLAMA_URL}/api/tags", timeout=3)
        if resp.status_code == 200:
            models = resp.json().get("models", [])
            model_names = [m["name"] for m in models]
            logger.info(f"Ollama local models found: {model_names}")
            
            # Find any model containing 'gemma'
            for m in model_names:
                if "gemma" in m.lower():
                    logger.info(f"Selected Gemma model: {m}")
                    return m
            
            # If no Gemma model found, pick the first available model
            if model_names:
                logger.warning(f"No Gemma model found, falling back to: {model_names[0]}")
                return model_names[0]
    except Exception as e:
        logger.warning(f"Failed to query Ollama list: {e}")
    return "gemma4:e2b"  # Default fallback name


def generate_gemma_advisory(
    sender: str,
    subject: str,
    verdict: str,
    urls: List[str],
    attachments: List[str]
) -> str:
    """
    Generates a security advisory using the local Gemma model.
    Falls back to a structured template if Ollama is offline.
    """
    model_name = get_installed_gemma_model()
    
    clean_urls = [url.split("?")[0] for url in urls]
    url_text = ", ".join(clean_urls[:3]) if clean_urls else "None"
    att_text = ", ".join(attachments) if attachments else "None"

    # Construct Prompt
    prompt = f"""You are an advanced AI Security Analyst. Write an urgent, direct security advisory warning for an employee who received a suspicious phishing email.

Email Details:
- Sender: {sender}
- Subject: {subject}
- Triage Verdict: {verdict}
- Extracted URLs: {url_text}
- Extracted Attachments: {att_text}

Provide your advisory in a concise, highly-readable layout (under 150 words) with the following structure:
1. ⚠️ WHY THIS IS DANGEROUS: Explain why this sender/email was flagged (homograph domain, lookalike, suspicious urgency).
2. 🚫 CRITICAL ACTIONS: Explicitly instruct them not to click the specific links ({url_text}) or open attachments ({att_text}).
3. 💥 TECHNICAL IMPACT: Tell them what happens if they click (e.g. keylogger steals credentials, session hijacking, or ransomware deployment).

Keep it professional, high-impact, and brief. Return ONLY the advisory text without any introductory greeting or AI meta-commentary.
"""

    payload = {
        "model": model_name,
        "prompt": prompt,
        "stream": False,
        "options": {
            "temperature": 0.3
        }
    }

    try:
        logger.info(f"Querying local Ollama model '{model_name}' for advisory...")
        resp = requests.post(f"{OLLAMA_URL}/api/generate", json=payload, timeout=15)
        if resp.status_code == 200:
            ai_text = resp.json().get("response", "").strip()
            if ai_text:
                logger.info("Advisory successfully generated by local Gemma LLM")
                return ai_text
    except Exception as e:
        logger.error(f"Failed to query Ollama: {e}. Falling back to rule-based advisory.")

    # Rule-Based Fallback Generator
    return generate_fallback_advisory(sender, subject, verdict, clean_urls, attachments)


def classify_security_verdict(
    sender: str,
    subject: str,
    body: str,
    urls: List[str],
    sender_trust: Dict[str, Any],
    enrichment_summary: Dict[str, Any]
) -> Dict[str, Any]:
    """Use Gemma as an additional security analyst signal for the triage verdict."""
    model_name = get_installed_gemma_model()
    trimmed_body = (body or "")[:4000]
    clean_urls = [url.split("?")[0] for url in (urls or [])[:5]]
    prompt = f"""You are a SOC email security analyst. Classify this email as MALICIOUS, SUSPICIOUS, or CLEAN.

Prioritize evidence in this order:
1. URL reputation and URL intent.
2. Body content, urgency, credential requests, malware delivery language, and impersonation.
3. Sender/TLS/certificate/domain authenticity signals.

Return strict JSON only:
{{"verdict":"MALICIOUS" or "SUSPICIOUS" or "CLEAN","confidence":0-100,"reason":"short reason"}}

Sender: {sender}
Subject: {subject}
Extracted URLs: {clean_urls}
Threat intel summary: {enrichment_summary}
Sender/TLS trust: {sender_trust}
Body:
{trimmed_body}
"""

    payload = {
        "model": model_name,
        "prompt": prompt,
        "stream": False,
        "options": {
            "temperature": 0.1
        }
    }

    try:
        logger.info(f"Querying local Ollama model '{model_name}' for security verdict classification...")
        resp = requests.post(f"{OLLAMA_URL}/api/generate", json=payload, timeout=12)
        if resp.status_code == 200:
            text = resp.json().get("response", "").strip()
            start = text.find("{")
            end = text.rfind("}")
            if start >= 0 and end >= start:
                data = json.loads(text[start:end + 1])
                verdict = str(data.get("verdict", "CLEAN")).upper().replace("-", "_").replace(" ", "_")
                if verdict not in ("MALICIOUS", "SUSPICIOUS", "CLEAN"):
                    verdict = "CLEAN"
                confidence = int(float(data.get("confidence", 0)))
                confidence = max(0, min(confidence, 100))
                return {
                    "verdict": verdict,
                    "confidence": confidence,
                    "reason": str(data.get("reason", ""))[:300],
                    "source": "gemma",
                }
    except Exception as e:
        logger.warning(f"Gemma security verdict failed: {e}. Falling back to local rules.")

    return fallback_security_verdict(subject, body, urls, sender_trust, enrichment_summary)


def fallback_security_verdict(
    subject: str,
    body: str,
    urls: List[str],
    sender_trust: Dict[str, Any],
    enrichment_summary: Dict[str, Any]
) -> Dict[str, Any]:
    """Simple offline security classifier when Gemma/Ollama is unavailable."""
    text = f"{subject or ''} {body or ''}".lower()
    malicious_terms = [
        "password", "verify your account", "login", "credential", "wire transfer",
        "invoice attached", "download", ".exe", "macro", "suspended", "urgent"
    ]
    hits = [term for term in malicious_terms if term in text]
    intel_malicious = int((enrichment_summary or {}).get("malicious", 0) or 0)
    intel_suspicious = int((enrichment_summary or {}).get("suspicious", 0) or 0)
    trust_level = (sender_trust or {}).get("trust_level", "TRUSTED")

    if intel_malicious > 0 or (urls and len(hits) >= 2) or trust_level == "SPOOFED":
        return {
            "verdict": "MALICIOUS",
            "confidence": min(95, 70 + len(hits) * 5),
            "reason": "URL/body/sender evidence indicates likely phishing or malware.",
            "source": "fallback_rules",
        }
    if intel_suspicious > 0 or hits or trust_level in ("SUSPICIOUS", "UNTRUSTED"):
        return {
            "verdict": "SUSPICIOUS",
            "confidence": min(85, 45 + len(hits) * 5),
            "reason": "Some suspicious body or sender indicators were found.",
            "source": "fallback_rules",
        }
    return {
        "verdict": "CLEAN",
        "confidence": 60,
        "reason": "No strong malicious, suspicious, or sender authenticity indicators were found.",
        "source": "fallback_rules",
    }


def generate_fallback_advisory(
    sender: str,
    subject: str,
    verdict: str,
    urls: List[str],
    attachments: List[str]
) -> str:
    """Fallback static template when Ollama/Gemma is not active."""
    url_text = ", ".join(urls[:2]) if urls else "None"
    att_text = ", ".join(attachments) if attachments else "None"
    
    advisory = f"### ⚠️ WHY THIS IS DANGEROUS\n"
    advisory += f"This email was flagged as **{verdict}** due to security anomalies. The sender address (`{sender}`) is unauthorized, represents a lookalike domain, or is known for phishing campaigns.\n\n"
    
    advisory += f"### 🚫 CRITICAL ACTIONS\n"
    if urls or attachments:
        advisory += "Do **NOT** under any circumstances click on the links or open attachments:\n"
        if urls:
            advisory += f"- **Do Not Click**: `{url_text}`\n"
        if attachments:
            advisory += f"- **Do Not Open**: `{att_text}`\n"
    else:
        advisory += "Do not click any embedded elements, links, or download resources in this message.\n"
    
    advisory += "\n### 💥 TECHNICAL IMPACT\n"
    if attachments:
        advisory += "Opening the attachment will execute malicious payloads (e.g. ransomware or info-stealers) directly onto your local environment, leading to full system compromise.\n"
    elif urls:
        advisory += "Visiting the lookalike URLs will lead to a credential-harvesting portal designed to steal your enterprise authentication tokens and allow unauthorized account takeover.\n"
    else:
        advisory += "Interaction with this message could trigger code execution vulnerabilities or notify the attacker that your address is active for future targeted attacks.\n"
        
    return advisory
